name: Build and Test
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # https://github.com/actions/checkout
        uses: actions/checkout@v6
      - name: Set up Go
        # https://github.com/actions/setup-go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Run Go Fmt
        run: make fmt
      - name: Run Go Vet
        run: make vet
      - name: Build
        run: go build -v ./...
      - name: Run Tests
        run: make test
